-- 코드를 입력하세요
-- 입양을 간 기록은 있는데, 보호소에 들어온 기록이 없는 동물
-- ID와 이름
-- ID 순으로 조회
-- SELECT OUTS.ANIMAL_ID, OUTS.NAME
-- FROM ANIMAL_INS INS RIGHT JOIN ANIMAL_OUTS OUTS
-- ON OUTS.ANIMAL_ID = INS.ANIMAL_ID(+)
-- WHERE OUTS.NAME =! ANY(SELECT NAME FROM ANIMAL_INS);

SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS LEFT JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID(+)
WHERE OUTS.ANIMAL_ID != ALL(SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY ANIMAL_ID;