-- 2년, 2월, 1성별 별로 2상품을 구매한 회원수
-- 결과는 년, 월, 성별을 기준으로 오름차순
-- 성별 정보가 없는 경우 결과에서 제외
-- JOIN으로 성별 포함시키고 GROUPING SETS로 그룹화

SELECT
TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH,
GENDER,
COUNT(DISTINCT OS.USER_ID) AS USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS
ON UI.USER_ID = OS.USER_ID
GROUP BY    GROUPING SETS   (TO_CHAR(SALES_DATE, 'YYYY')), 
                            (TO_CHAR(SALES_DATE, 'MM')),
                            GENDER
HAVING GENDER IS NOT NULL
ORDER BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER



-- SELECT 
-- TO_CHAR(SALES_DATE, 'YY') AS Y, 
-- TO_CHAR(SALES_DATE, 'MM') AS M,  
-- COUNT(USER_ID) AS USERS
-- FROM ONLINE_SALE
-- GROUP BY    GROUPING SETS   (TO_CHAR(SALES_DATE, 'YY')), 
--                             (TO_CHAR(SALES_DATE, 'MM'))
-- ORDER BY TO_CHAR(SALES_DATE, 'YY'), TO_CHAR(SALES_DATE, 'MM')