-- 코드를 입력하세요
-- 음식 종류(한식, 양식, 일식)별로 각각 FAVORITES 값이 가장 많은 식당의 
-- 음식 종류, ID, 식당이름, 즐겨찾기 수를 조회

SELECT T1.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, T1.FAVORITES
FROM
(SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
FROM REST_INFO
GROUP BY  FOOD_TYPE) T1 JOIN REST_INFO RI
ON T1.FAVORITES = RI.FAVORITES
AND T1.FOOD_TYPE = RI.FOOD_TYPE
ORDER BY FOOD_TYPE DESC