-- 코드를 입력하세요
SELECT * FROM
(
    SELECT OUTS.ANIMAL_ID, OUTS.NAME
    FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE INS.NAME = ANY(SELECT NAME FROM ANIMAL_OUTS)
    ORDER BY OUTS.DATETIME - INS.DATETIME DESC
)
WHERE ROWNUM <= 2;