-- 코드를 입력하세요
-- 완료된 중고거래의 총 금액이 70만원 이상
-- 아이디, 닉넴, 총거래금액
-- 총거래금액 오름차순
-- JOIN 먼저, GROUP BY 그 다음
-- SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS TOTAL_SALES
-- FROM USED_GOODS_BOARD
-- WHERE STATUS = 'DONE'
-- GROUP BY WRITER_ID
-- HAVING SUM(PRICE) >= 700000
-- ORDER BY SUM(PRICE);

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM
(
SELECT *
FROM USED_GOODS_BOARD B JOIN USED_GOODS_USER U
ON WRITER_ID = USER_ID
WHERE STATUS = 'DONE'
)
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE);