-- 코드를 입력하세요
-- 2022년 9월 대여 기록
-- 대여기간 30일 이상 -> 장기 대여
-- 그렇지 않으면 -> 단기 대여
-- 장/단기 대여 여부는 RENT_TYPE 컬럼에 구현

-- SELECT HISTORY_ID, CAR_ID, START_DATE, END_DATE
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- WHERE TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09' 

SELECT HISTORY_ID, CAR_ID, 
TO_CHAR(START_DATE, 'YYYY-MM-DD') AS START_DATE, 
TO_CHAR(END_DATE, 'YYYY-MM-DD') AS END_DATE,
    CASE
    WHEN END_DATE - START_DATE + 1 >= 30 THEN '장기 대여'
    WHEN (END_DATE - START_DATE + 1) BETWEEN 1 AND 29 THEN '단기 대여'
    END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE TO_CHAR(START_DATE, 'YYYY-MM') = '2022-09'
ORDER BY HISTORY_ID DESC;