-- 생산일자가 2022년 5월
-- 식품 ID, 식품 이름, 총매출
-- 총매출을 기준으로 내림차순 -> 식품 ID를 기준으로 오름차순
SELECT T1.PRODUCT_ID, FP2.PRODUCT_NAME, T1.TOTAL_SALES
FROM
(
SELECT FO.PRODUCT_ID, SUM(AMOUNT*PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') = '2022-05'
GROUP BY FO.PRODUCT_ID
) T1 JOIN FOOD_PRODUCT FP2
ON T1.PRODUCT_ID = FP2.PRODUCT_ID
ORDER BY T1.TOTAL_SALES DESC, T1.PRODUCT_ID;